// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsqevAruYHnwm_R7pHOaJiC2YFOrQOM40',
    appId: '1:805956295423:web:1d4281230f85d5aa558aca',
    messagingSenderId: '805956295423',
    projectId: 'pareja-play',
    authDomain: 'pareja-play.firebaseapp.com',
    storageBucket: 'pareja-play.firebasestorage.app',
    measurementId: 'G-C796F2E97N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADlvA8AZKRaUc102wr2OXj-Wdq2LFMCWI',
    appId: '1:805956295423:android:2a5b382f1c7bf325558aca',
    messagingSenderId: '805956295423',
    projectId: 'pareja-play',
    storageBucket: 'pareja-play.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHVonwipYCr2RssXadk6blK8UEnfBmSlI',
    appId: '1:805956295423:ios:d985d4198d477a3d558aca',
    messagingSenderId: '805956295423',
    projectId: 'pareja-play',
    storageBucket: 'pareja-play.firebasestorage.app',
    iosBundleId: 'com.lovequiz.app',
  );
}
